(declare-datatypes ((_enum_2 0)) (((INT) (BOOL) (UNKNOWN))))
(declare-datatypes ((_enum_0 0)) (((A) (B) (C) (NULL))))
(declare-datatypes ((_enum_1 0)) (((A_STARTUP) (B_STARTUP) (B_IN) (C_STARTUP) (C_IN) (NULL_NULL))))
(declare-datatypes ((_tuple_1 0)) (((_tuple_1 (__f1 Int) (__f2 _enum_0) (__f3 _enum_0) (__f4 _enum_1) (__f5 _enum_2) (__f6 Int) (__f7 Bool)))))
(declare-datatypes ((_tuple_0 0)) (((_tuple_0 (__f1 _tuple_1) (__f2 _tuple_1) (__f3 _tuple_1) (__f4 _tuple_1) (__f5 _tuple_1)))))
(declare-fun initial_28_s_to_a () _tuple_0)
(declare-fun havoc_87___ucld_84_test_z () Bool)
(declare-fun havoc_88___ucld_83_test_z () Bool)
(declare-fun havoc_89___ucld_85_test_pending () Bool)
(assert (= initial_28_s_to_a
   (_tuple_0 (_tuple_1 (- 1) NULL NULL NULL_NULL UNKNOWN (- 1) false)
             (_tuple_1 (- 1) NULL NULL NULL_NULL UNKNOWN (- 1) false)
             (_tuple_1 (- 1) NULL NULL NULL_NULL UNKNOWN (- 1) false)
             (_tuple_1 (- 1) NULL NULL NULL_NULL UNKNOWN (- 1) false)
             (_tuple_1 (- 1) NULL NULL NULL_NULL UNKNOWN (- 1) false))))
(assert havoc_87___ucld_84_test_z)
(assert (not havoc_88___ucld_83_test_z))
(assert (not (and (or havoc_87___ucld_84_test_z havoc_89___ucld_85_test_pending)
          (not havoc_88___ucld_83_test_z))))


(check-sat)
(get-model)
(get-info :all-statistics)
