// Code generated by the Lingua Franca compiler from file:
// /Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf
#include "pqueue.c"
#define NUMBER_OF_FEDERATES 1
#include "reactor.c"
// =============== START reactor class A
typedef struct {
    #line 4 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    int ___out;
    #line 4 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    bool ___out_is_present;
    #line 4 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    int ___out_num_destinations;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    reaction_t ___reaction_0;
    bool* __reaction_0_outputs_are_present[1];
    int __reaction_0_num_outputs;
    trigger_t** __reaction_0_triggers[1];
    int __reaction_0_triggered_sizes[1];
    trigger_t ___startup;
    reaction_t* ___startup_reactions[1];
} a_self_t;
void areaction_function_0(void* instance_args) {
    a_self_t* self = (a_self_t*)instance_args;
    int* _out = &(self->___out);
    bool _out_is_present = self->___out_is_present;
    #line 7 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    set(_out, 1);
        
}
a_self_t* new_A() {
    a_self_t* self = (a_self_t*)calloc(1, sizeof(a_self_t));
    self->__reaction_0_outputs_are_present[0] = &self->___out_is_present;
    self->__reaction_0_num_outputs = 1;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.function = areaction_function_0;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.self = self;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.num_outputs = 1;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.output_produced = self->__reaction_0_outputs_are_present;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.triggered_sizes = self->__reaction_0_triggered_sizes;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.triggers = self->__reaction_0_triggers;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    self->___startup.scheduled = NEVER;
    self->___startup_reactions[0] = &self->___reaction_0;
    self->___startup.reactions = &self->___startup_reactions[0];
    self->___startup.number_of_reactions = 1;
    self->___startup.is_timer = true;
    return self;
}
// =============== END reactor class A

// =============== START reactor class B
typedef struct {
    #line 13 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    int s;
    #line 12 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    int* ___in;
    #line 12 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    bool* ___in_is_present;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    reaction_t ___reaction_0;
    bool* __reaction_0_outputs_are_present[0];
    int __reaction_0_num_outputs;
    trigger_t** __reaction_0_triggers[0];
    int __reaction_0_triggered_sizes[0];
    #line 12 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    trigger_t ____in;
    #line 12 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    reaction_t* ____in_reactions[1];
} b_self_t;
void breaction_function_0(void* instance_args) {
    b_self_t* self = (b_self_t*)instance_args;
    bool _in_is_present = *(self->___in_is_present);
    int _in;
    if (_in_is_present) {
                           _in = *(self->___in);
    }
    #line 15 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->s = self->s + _in;
    printf("%d\n", self->s);
        
}
b_self_t* new_B() {
    b_self_t* self = (b_self_t*)calloc(1, sizeof(b_self_t));
    self->__reaction_0_num_outputs = 0;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.function = breaction_function_0;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.self = self;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.num_outputs = 0;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.output_produced = self->__reaction_0_outputs_are_present;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.triggered_sizes = self->__reaction_0_triggered_sizes;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.triggers = self->__reaction_0_triggers;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 12 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->____in.scheduled = NEVER;
    #line 12 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B.lf"
    self->____in_reactions[0] = &self->___reaction_0;
    self->____in.reactions = &self->____in_reactions[0];
    self->____in.number_of_reactions = 1;
    self->____in.element_size = sizeof(int);
    return self;
}
// =============== END reactor class B

// =============== START reactor class Composition
typedef struct {
    bool hasContents;
} composition_self_t;
composition_self_t* new_Composition() {
    composition_self_t* self = (composition_self_t*)calloc(1, sizeof(composition_self_t));
    return self;
}
// =============== END reactor class Composition

void __set_default_command_line_options() {
}
// Array of pointers to timer triggers to start the timers in __start_timers().
trigger_t* __timer_triggers[1];
int __timer_triggers_size = 1;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    // Create the array that will contain pointers to _is_present fields to reset on each step.
    __is_present_fields_size = 1;
    __is_present_fields = (bool**)malloc(1 * sizeof(bool*));
    // ************* Instance Composition of class Composition
    composition_self_t* composition_self = new_Composition();
    //***** Start initializing Composition
    // ************* Instance Composition.a of class A
    a_self_t* composition_a_self = new_A();
    //***** Start initializing Composition.a
    // Reaction 0 of Composition.a triggers 1 downstream reactions through port Composition.a._out.
    composition_a_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of Composition.a, allocate an
    // array of trigger pointers for downstream reactions through port Composition.a._out
    trigger_t** composition_a_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    composition_a_self->___reaction_0.triggers[0] = composition_a_0_0;
    composition_a_self->___startup.offset = 0;
    composition_a_self->___startup.period = 0;
    __timer_triggers[0] = &composition_a_self->___startup;
    composition_a_self->___out_num_destinations = 1;
    //***** End initializing Composition.a
    // ************* Instance Composition.b of class B
    b_self_t* composition_b_self = new_B();
    //***** Start initializing Composition.b
    static int composition_b_initial_s = 0;
    composition_b_self->s = composition_b_initial_s;
    //***** End initializing Composition.b
    //***** End initializing Composition
    // Populate arrays of trigger pointers.
    // Point to destination port Composition.b._in's trigger struct.
    composition_a_0_0[0] = &composition_b_self->____in;
    // doDeferredInitialize
    composition_b_self->___in_is_present = &absent;
    // Connect inputs and outputs for reactor Composition.
    // Connect Composition.a._out to input port Composition.b._in
    composition_b_self->___in = &composition_a_self->___out;
    composition_b_self->___in_is_present = &composition_a_self->___out_is_present;
    // Connect inputs and outputs for reactor Composition.a.
    // END Connect inputs and outputs for reactor Composition.a.
    // Connect inputs and outputs for reactor Composition.b.
    // END Connect inputs and outputs for reactor Composition.b.
    // END Connect inputs and outputs for reactor Composition.
    // Add port Composition.a._out to array of _is_present fields.
    __is_present_fields[0] = &composition_a_self->___out_is_present;
    composition_a_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    composition_a_self->___reaction_0.index = 0x7fffffffffff0000LL;
    composition_b_self->___reaction_0.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    composition_b_self->___reaction_0.index = 0x7fffffffffff0001LL;
}
void __start_timers() {
    
    for (int i = 0; i < __timer_triggers_size; i++) {
        __schedule(__timer_triggers[i], 0LL, NULL);
    }
}
void logical_time_complete(instant_t time) {
}
instant_t next_event_time(instant_t time) {
    return time;
}
bool __wrapup() {
    __start_time_step();   // To free memory allocated for actions.
    return false;
}
void __termination() {}
