// Code generated by the Lingua Franca compiler from file:
// /Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf
#include "pqueue.c"
#define NUMBER_OF_FEDERATES 1
#include "reactor.c"
// =============== START reactor class A
typedef struct {
    #line 10 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    int ___out;
    #line 10 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    bool ___out_is_present;
    #line 10 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    int ___out_num_destinations;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    reaction_t ___reaction_0;
    bool* __reaction_0_outputs_are_present[1];
    int __reaction_0_num_outputs;
    trigger_t** __reaction_0_triggers[1];
    int __reaction_0_triggered_sizes[1];
    #line 20 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    reaction_t ___reaction_1;
    bool* __reaction_1_outputs_are_present[0];
    int __reaction_1_num_outputs;
    trigger_t** __reaction_1_triggers[0];
    int __reaction_1_triggered_sizes[0];
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    reaction_t ___reaction_2;
    bool* __reaction_2_outputs_are_present[0];
    int __reaction_2_num_outputs;
    trigger_t** __reaction_2_triggers[0];
    int __reaction_2_triggered_sizes[0];
    trigger_t ___startup;
    reaction_t* ___startup_reactions[1];
    #line 11 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    trigger_t ___foo;
    #line 11 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    reaction_t* ___foo_reactions[1];
    #line 12 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    trigger_t ___bar;
    #line 12 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    reaction_t* ___bar_reactions[1];
} a_self_t;
void areaction_function_0(void* instance_args) {
    a_self_t* self = (a_self_t*)instance_args;
    int* _out = &(self->___out);
    bool _out_is_present = self->___out_is_present;
    trigger_t* foo = &self->___foo;
    trigger_t* bar = &self->___bar;
    #line 15 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    set(_out, 0);
    schedule(foo, 2);
    schedule(bar, 1);
        
}
void areaction_function_1(void* instance_args) {
    a_self_t* self = (a_self_t*)instance_args;
    bool foo_is_present = self->___foo.is_present;
    bool foo_has_value = ((self->___foo.token) != NULL && (self->___foo.token)->value != NULL);
    token_t* foo_token = (self->___foo.token);
    #line 21 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    printf("I am foo.\n");
        
}
void areaction_function_2(void* instance_args) {
    a_self_t* self = (a_self_t*)instance_args;
    bool bar_is_present = self->___bar.is_present;
    bool bar_has_value = ((self->___bar.token) != NULL && (self->___bar.token)->value != NULL);
    token_t* bar_token = (self->___bar.token);
    #line 25 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    printf("I am bar.\n");
        
}
a_self_t* new_A() {
    a_self_t* self = (a_self_t*)calloc(1, sizeof(a_self_t));
    self->__reaction_0_outputs_are_present[0] = &self->___out_is_present;
    self->__reaction_0_num_outputs = 1;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.function = areaction_function_0;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.self = self;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.num_outputs = 1;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.output_produced = self->__reaction_0_outputs_are_present;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.triggered_sizes = self->__reaction_0_triggered_sizes;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.triggers = self->__reaction_0_triggers;
    #line 14 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    self->__reaction_1_num_outputs = 0;
    #line 20 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_1.function = areaction_function_1;
    #line 20 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_1.self = self;
    #line 20 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_1.num_outputs = 0;
    #line 20 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_1.output_produced = self->__reaction_1_outputs_are_present;
    #line 20 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_1.triggered_sizes = self->__reaction_1_triggered_sizes;
    #line 20 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_1.triggers = self->__reaction_1_triggers;
    #line 20 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_1.deadline_violation_handler = NULL;
    self->__reaction_2_num_outputs = 0;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_2.function = areaction_function_2;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_2.self = self;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_2.num_outputs = 0;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_2.output_produced = self->__reaction_2_outputs_are_present;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_2.triggered_sizes = self->__reaction_2_triggered_sizes;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_2.triggers = self->__reaction_2_triggers;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_2.deadline_violation_handler = NULL;
    self->___startup.scheduled = NEVER;
    self->___startup_reactions[0] = &self->___reaction_0;
    self->___startup.reactions = &self->___startup_reactions[0];
    self->___startup.number_of_reactions = 1;
    self->___startup.is_timer = true;
    #line 11 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___foo.scheduled = NEVER;
    #line 11 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___foo_reactions[0] = &self->___reaction_1;
    self->___foo.reactions = &self->___foo_reactions[0];
    self->___foo.number_of_reactions = 1;
    self->___foo.is_physical = false;
    self->___foo.drop = false;
    self->___foo.element_size = 0;
    #line 12 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___bar.scheduled = NEVER;
    #line 12 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___bar_reactions[0] = &self->___reaction_2;
    self->___bar.reactions = &self->___bar_reactions[0];
    self->___bar.number_of_reactions = 1;
    self->___bar.is_physical = false;
    self->___bar.drop = false;
    self->___bar.element_size = 0;
    return self;
}
// =============== END reactor class A

// =============== START reactor class B
typedef struct {
    #line 31 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    int* ___in;
    #line 31 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    bool* ___in_is_present;
    #line 33 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    reaction_t ___reaction_0;
    bool* __reaction_0_outputs_are_present[0];
    int __reaction_0_num_outputs;
    trigger_t** __reaction_0_triggers[0];
    int __reaction_0_triggered_sizes[0];
    #line 31 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    trigger_t ____in;
    #line 31 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    reaction_t* ____in_reactions[1];
} b_self_t;
void breaction_function_0(void* instance_args) {
    b_self_t* self = (b_self_t*)instance_args;
    bool _in_is_present = *(self->___in_is_present);
    int _in;
    if (_in_is_present) {
                           _in = *(self->___in);
    }
    #line 34 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    printf("Received %d from A\n", _in);
        
}
b_self_t* new_B() {
    b_self_t* self = (b_self_t*)calloc(1, sizeof(b_self_t));
    self->__reaction_0_num_outputs = 0;
    #line 33 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.function = breaction_function_0;
    #line 33 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.self = self;
    #line 33 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.num_outputs = 0;
    #line 33 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.output_produced = self->__reaction_0_outputs_are_present;
    #line 33 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.triggered_sizes = self->__reaction_0_triggered_sizes;
    #line 33 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.triggers = self->__reaction_0_triggers;
    #line 33 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 31 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->____in.scheduled = NEVER;
    #line 31 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_B_action.lf"
    self->____in_reactions[0] = &self->___reaction_0;
    self->____in.reactions = &self->____in_reactions[0];
    self->____in.number_of_reactions = 1;
    self->____in.element_size = sizeof(int);
    return self;
}
// =============== END reactor class B

// =============== START reactor class Composition
typedef struct {
    bool hasContents;
} composition_self_t;
composition_self_t* new_Composition() {
    composition_self_t* self = (composition_self_t*)calloc(1, sizeof(composition_self_t));
    return self;
}
// =============== END reactor class Composition

void __set_default_command_line_options() {
}
// Array of pointers to timer triggers to start the timers in __start_timers().
trigger_t* __timer_triggers[1];
int __timer_triggers_size = 1;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    __tokens_with_ref_count_size = 2;
    __tokens_with_ref_count = (token_present_t*)malloc(2 * sizeof(token_present_t));
    // Create the array that will contain pointers to _is_present fields to reset on each step.
    __is_present_fields_size = 1;
    __is_present_fields = (bool**)malloc(1 * sizeof(bool*));
    // ************* Instance Composition of class Composition
    composition_self_t* composition_self = new_Composition();
    //***** Start initializing Composition
    // ************* Instance Composition.a of class A
    a_self_t* composition_a_self = new_A();
    //***** Start initializing Composition.a
    // Reaction 0 of Composition.a triggers 1 downstream reactions through port Composition.a._out.
    composition_a_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of Composition.a, allocate an
    // array of trigger pointers for downstream reactions through port Composition.a._out
    trigger_t** composition_a_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    composition_a_self->___reaction_0.triggers[0] = composition_a_0_0;
    composition_a_self->___foo.offset = 0;
    composition_a_self->___foo.period = 0;
    composition_a_self->___bar.offset = 0;
    composition_a_self->___bar.period = 0;
    composition_a_self->___startup.offset = 0;
    composition_a_self->___startup.period = 0;
    __timer_triggers[0] = &composition_a_self->___startup;
    composition_a_self->___out_num_destinations = 1;
    composition_a_self->___foo.token = __create_token(0);
    composition_a_self->___foo.is_present = false;
    __tokens_with_ref_count[0].token
            = &composition_a_self->___foo.token;
    __tokens_with_ref_count[0].is_present
            = &composition_a_self->___foo.is_present;
    __tokens_with_ref_count[0].reset_is_present = true;
    composition_a_self->___bar.token = __create_token(0);
    composition_a_self->___bar.is_present = false;
    __tokens_with_ref_count[1].token
            = &composition_a_self->___bar.token;
    __tokens_with_ref_count[1].is_present
            = &composition_a_self->___bar.is_present;
    __tokens_with_ref_count[1].reset_is_present = true;
    //***** End initializing Composition.a
    // ************* Instance Composition.b of class B
    b_self_t* composition_b_self = new_B();
    //***** Start initializing Composition.b
    //***** End initializing Composition.b
    //***** End initializing Composition
    // Populate arrays of trigger pointers.
    // Point to destination port Composition.b._in's trigger struct.
    composition_a_0_0[0] = &composition_b_self->____in;
    // doDeferredInitialize
    composition_b_self->___in_is_present = &absent;
    // Connect inputs and outputs for reactor Composition.
    // Connect Composition.a._out to input port Composition.b._in
    composition_b_self->___in = &composition_a_self->___out;
    composition_b_self->___in_is_present = &composition_a_self->___out_is_present;
    // Connect inputs and outputs for reactor Composition.a.
    // END Connect inputs and outputs for reactor Composition.a.
    // Connect inputs and outputs for reactor Composition.b.
    // END Connect inputs and outputs for reactor Composition.b.
    // END Connect inputs and outputs for reactor Composition.
    // Add port Composition.a._out to array of _is_present fields.
    __is_present_fields[0] = &composition_a_self->___out_is_present;
    composition_a_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    composition_a_self->___reaction_0.index = 0x7fffffffffff0000LL;
    composition_a_self->___reaction_1.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    composition_a_self->___reaction_1.index = 0x7fffffffffff0001LL;
    composition_a_self->___reaction_2.chain_id = 1;
    // index is the OR of level 2 and 
    // deadline 140737488355327 shifted left 16 bits.
    composition_a_self->___reaction_2.index = 0x7fffffffffff0002LL;
    composition_b_self->___reaction_0.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    composition_b_self->___reaction_0.index = 0x7fffffffffff0001LL;
}
void __start_timers() {
    
    for (int i = 0; i < __timer_triggers_size; i++) {
        __schedule(__timer_triggers[i], 0LL, NULL);
    }
}
void logical_time_complete(instant_t time) {
}
instant_t next_event_time(instant_t time) {
    return time;
}
bool __wrapup() {
    __start_time_step();   // To free memory allocated for actions.
    return false;
}
void __termination() {}
