// Code generated by the Lingua Franca compiler from file:
// /Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf
#include "pqueue.c"
#define NUMBER_OF_FEDERATES 1
#include "reactor.c"
// =============== START reactor class A
typedef struct {
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    reaction_t ___reaction_0;
    bool* __reaction_0_outputs_are_present[0];
    int __reaction_0_num_outputs;
    trigger_t** __reaction_0_triggers[0];
    int __reaction_0_triggered_sizes[0];
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    reaction_t ___reaction_1;
    bool* __reaction_1_outputs_are_present[0];
    int __reaction_1_num_outputs;
    trigger_t** __reaction_1_triggers[0];
    int __reaction_1_triggered_sizes[0];
    trigger_t ___startup;
    reaction_t* ___startup_reactions[1];
    #line 4 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    trigger_t ___foo;
    #line 4 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    reaction_t* ___foo_reactions[1];
} a_self_t;
void areaction_function_0(void* instance_args) {
    a_self_t* self = (a_self_t*)instance_args;
    trigger_t* foo = &self->___foo;
    #line 7 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    schedule(foo, 5);
        
}
void areaction_function_1(void* instance_args) {
    a_self_t* self = (a_self_t*)instance_args;
    bool foo_is_present = self->___foo.is_present;
    bool foo_has_value = ((self->___foo.token) != NULL && (self->___foo.token)->value != NULL);
    token_t* foo_token = (self->___foo.token);
    #line 10 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    printf("I am a delayed reaction.\n"); 
        
}
a_self_t* new_A() {
    a_self_t* self = (a_self_t*)calloc(1, sizeof(a_self_t));
    self->__reaction_0_num_outputs = 0;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_0.function = areaction_function_0;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_0.self = self;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_0.num_outputs = 0;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_0.output_produced = self->__reaction_0_outputs_are_present;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_0.triggered_sizes = self->__reaction_0_triggered_sizes;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_0.triggers = self->__reaction_0_triggers;
    #line 6 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    self->__reaction_1_num_outputs = 0;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_1.function = areaction_function_1;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_1.self = self;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_1.num_outputs = 0;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_1.output_produced = self->__reaction_1_outputs_are_present;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_1.triggered_sizes = self->__reaction_1_triggered_sizes;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_1.triggers = self->__reaction_1_triggers;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___reaction_1.deadline_violation_handler = NULL;
    self->___startup.scheduled = NEVER;
    self->___startup_reactions[0] = &self->___reaction_0;
    self->___startup.reactions = &self->___startup_reactions[0];
    self->___startup.number_of_reactions = 1;
    self->___startup.is_timer = true;
    #line 4 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___foo.scheduled = NEVER;
    #line 4 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/A_delayed.lf"
    self->___foo_reactions[0] = &self->___reaction_1;
    self->___foo.reactions = &self->___foo_reactions[0];
    self->___foo.number_of_reactions = 1;
    self->___foo.is_physical = false;
    self->___foo.drop = false;
    self->___foo.element_size = 0;
    return self;
}
// =============== END reactor class A

// =============== START reactor class Composition
typedef struct {
    bool hasContents;
} composition_self_t;
composition_self_t* new_Composition() {
    composition_self_t* self = (composition_self_t*)calloc(1, sizeof(composition_self_t));
    return self;
}
// =============== END reactor class Composition

void __set_default_command_line_options() {
}
// Array of pointers to timer triggers to start the timers in __start_timers().
trigger_t* __timer_triggers[1];
int __timer_triggers_size = 1;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    __tokens_with_ref_count_size = 1;
    __tokens_with_ref_count = (token_present_t*)malloc(1 * sizeof(token_present_t));
    // ************* Instance Composition of class Composition
    composition_self_t* composition_self = new_Composition();
    //***** Start initializing Composition
    // ************* Instance Composition.a of class A
    a_self_t* composition_a_self = new_A();
    //***** Start initializing Composition.a
    composition_a_self->___startup.offset = 0;
    composition_a_self->___startup.period = 0;
    __timer_triggers[0] = &composition_a_self->___startup;
    composition_a_self->___foo.offset = 0;
    composition_a_self->___foo.period = 0;
    composition_a_self->___foo.token = __create_token(0);
    composition_a_self->___foo.is_present = false;
    __tokens_with_ref_count[0].token
            = &composition_a_self->___foo.token;
    __tokens_with_ref_count[0].is_present
            = &composition_a_self->___foo.is_present;
    __tokens_with_ref_count[0].reset_is_present = true;
    //***** End initializing Composition.a
    //***** End initializing Composition
    // Populate arrays of trigger pointers.
    
    // doDeferredInitialize
    // Connect inputs and outputs for reactor Composition.
    // Connect inputs and outputs for reactor Composition.a.
    // END Connect inputs and outputs for reactor Composition.a.
    // END Connect inputs and outputs for reactor Composition.
    
    composition_a_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    composition_a_self->___reaction_0.index = 0x7fffffffffff0000LL;
    composition_a_self->___reaction_1.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    composition_a_self->___reaction_1.index = 0x7fffffffffff0001LL;
}
void __start_timers() {
    
    for (int i = 0; i < __timer_triggers_size; i++) {
        __schedule(__timer_triggers[i], 0LL, NULL);
    }
}
void logical_time_complete(instant_t time) {
}
instant_t next_event_time(instant_t time) {
    return time;
}
bool __wrapup() {
    __start_time_step();   // To free memory allocated for actions.
    return false;
}
void __termination() {}
