// Code generated by the Lingua Franca compiler from file:
// /Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf
#include "pqueue.c"
#define NUMBER_OF_FEDERATES 1
#include "reactor.c"
// =============== START reactor class A
typedef struct {
    #line 8 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    int ___out;
    #line 8 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    bool ___out_is_present;
    #line 8 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    int ___out_num_destinations;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    reaction_t ___reaction_0;
    bool* __reaction_0_outputs_are_present[1];
    int __reaction_0_num_outputs;
    trigger_t** __reaction_0_triggers[1];
    int __reaction_0_triggered_sizes[1];
    trigger_t ___startup;
    reaction_t* ___startup_reactions[1];
} a_self_t;
void areaction_function_0(void* instance_args) {
    a_self_t* self = (a_self_t*)instance_args;
    int* _out = &(self->___out);
    bool _out_is_present = self->___out_is_present;
    #line 10 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    set(_out, 1);
        
}
a_self_t* new_A() {
    a_self_t* self = (a_self_t*)calloc(1, sizeof(a_self_t));
    self->__reaction_0_outputs_are_present[0] = &self->___out_is_present;
    self->__reaction_0_num_outputs = 1;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.function = areaction_function_0;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.self = self;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.num_outputs = 1;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.output_produced = self->__reaction_0_outputs_are_present;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.triggered_sizes = self->__reaction_0_triggered_sizes;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.triggers = self->__reaction_0_triggers;
    #line 9 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    self->___startup.scheduled = NEVER;
    self->___startup_reactions[0] = &self->___reaction_0;
    self->___startup.reactions = &self->___startup_reactions[0];
    self->___startup.number_of_reactions = 1;
    self->___startup.is_timer = true;
    return self;
}
// =============== END reactor class A

// =============== START reactor class B
typedef struct {
    #line 15 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    int* ___in;
    #line 15 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    bool* ___in_is_present;
    #line 16 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    int ___out;
    #line 16 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    bool ___out_is_present;
    #line 16 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    int ___out_num_destinations;
    #line 17 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    reaction_t ___reaction_0;
    bool* __reaction_0_outputs_are_present[1];
    int __reaction_0_num_outputs;
    trigger_t** __reaction_0_triggers[1];
    int __reaction_0_triggered_sizes[1];
    #line 15 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    trigger_t ____in;
    #line 15 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    reaction_t* ____in_reactions[1];
} b_self_t;
void breaction_function_0(void* instance_args) {
    b_self_t* self = (b_self_t*)instance_args;
    bool _in_is_present = *(self->___in_is_present);
    int _in;
    if (_in_is_present) {
                           _in = *(self->___in);
    }
    int* _out = &(self->___out);
    bool _out_is_present = self->___out_is_present;
    #line 18 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    set(_out, _in);
        
}
b_self_t* new_B() {
    b_self_t* self = (b_self_t*)calloc(1, sizeof(b_self_t));
    self->__reaction_0_outputs_are_present[0] = &self->___out_is_present;
    self->__reaction_0_num_outputs = 1;
    #line 17 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.function = breaction_function_0;
    #line 17 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.self = self;
    #line 17 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.num_outputs = 1;
    #line 17 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.output_produced = self->__reaction_0_outputs_are_present;
    #line 17 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.triggered_sizes = self->__reaction_0_triggered_sizes;
    #line 17 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.triggers = self->__reaction_0_triggers;
    #line 17 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 15 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->____in.scheduled = NEVER;
    #line 15 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->____in_reactions[0] = &self->___reaction_0;
    self->____in.reactions = &self->____in_reactions[0];
    self->____in.number_of_reactions = 1;
    self->____in.element_size = sizeof(int);
    return self;
}
// =============== END reactor class B

// =============== START reactor class C
typedef struct {
    #line 23 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    int* ___in;
    #line 23 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    bool* ___in_is_present;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    reaction_t ___reaction_0;
    bool* __reaction_0_outputs_are_present[0];
    int __reaction_0_num_outputs;
    trigger_t** __reaction_0_triggers[0];
    int __reaction_0_triggered_sizes[0];
    #line 23 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    trigger_t ____in;
    #line 23 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    reaction_t* ____in_reactions[1];
} c_self_t;
void creaction_function_0(void* instance_args) {
    c_self_t* self = (c_self_t*)instance_args;
    bool _in_is_present = *(self->___in_is_present);
    int _in;
    if (_in_is_present) {
                           _in = *(self->___in);
    }
    #line 25 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    printf("%d\n", _in);
        
}
c_self_t* new_C() {
    c_self_t* self = (c_self_t*)calloc(1, sizeof(c_self_t));
    self->__reaction_0_num_outputs = 0;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.function = creaction_function_0;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.self = self;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.num_outputs = 0;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.output_produced = self->__reaction_0_outputs_are_present;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.triggered_sizes = self->__reaction_0_triggered_sizes;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.triggers = self->__reaction_0_triggers;
    #line 24 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 23 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->____in.scheduled = NEVER;
    #line 23 "file:/Users/shaokai/Documents/projects/lingua-franca/lf-fv/uclid/lf/chained_reactor.lf"
    self->____in_reactions[0] = &self->___reaction_0;
    self->____in.reactions = &self->____in_reactions[0];
    self->____in.number_of_reactions = 1;
    self->____in.element_size = sizeof(int);
    return self;
}
// =============== END reactor class C

// =============== START reactor class __GenDelay_197ef
typedef struct {
    interval_t delay;
    int* __inp;
    bool* __inp_is_present;
    int __out;
    bool __out_is_present;
    int __out_num_destinations;
    reaction_t ___reaction_0;
    bool* __reaction_0_outputs_are_present[1];
    int __reaction_0_num_outputs;
    trigger_t** __reaction_0_triggers[1];
    int __reaction_0_triggered_sizes[1];
    reaction_t ___reaction_1;
    bool* __reaction_1_outputs_are_present[0];
    int __reaction_1_num_outputs;
    trigger_t** __reaction_1_triggers[0];
    int __reaction_1_triggered_sizes[0];
    trigger_t ___act;
    reaction_t* ___act_reactions[1];
    trigger_t ___inp;
    reaction_t* ___inp_reactions[1];
} __gendelay_197ef_self_t;
void __gendelay_197efreaction_function_0(void* instance_args) {
    __gendelay_197ef_self_t* self = (__gendelay_197ef_self_t*)instance_args;
    bool act_is_present = self->___act.is_present;
    bool act_has_value = ((self->___act.token) != NULL && (self->___act.token)->value != NULL);
    token_t* act_token = (self->___act.token);
    int act_value;
    if (act_has_value) {
        act_value = *((int*)(self->___act.token)->value);
    }
    int* out = &(self->__out);
    bool out_is_present = self->__out_is_present;
    set(out, act_value);
}
void __gendelay_197efreaction_function_1(void* instance_args) {
    __gendelay_197ef_self_t* self = (__gendelay_197ef_self_t*)instance_args;
    bool inp_is_present = *(self->__inp_is_present);
    int inp;
    if (inp_is_present) {
                           inp = *(self->__inp);
    }
    trigger_t* act = &self->___act;
    schedule_copy(act, 0, &inp, 1);  // Length is 1.
}
__gendelay_197ef_self_t* new___GenDelay_197ef() {
    __gendelay_197ef_self_t* self = (__gendelay_197ef_self_t*)calloc(1, sizeof(__gendelay_197ef_self_t));
    self->__reaction_0_outputs_are_present[0] = &self->__out_is_present;
    self->__reaction_0_num_outputs = 1;
    self->___reaction_0.function = __gendelay_197efreaction_function_0;
    self->___reaction_0.self = self;
    self->___reaction_0.num_outputs = 1;
    self->___reaction_0.output_produced = self->__reaction_0_outputs_are_present;
    self->___reaction_0.triggered_sizes = self->__reaction_0_triggered_sizes;
    self->___reaction_0.triggers = self->__reaction_0_triggers;
    self->___reaction_0.deadline_violation_handler = NULL;
    self->__reaction_1_num_outputs = 0;
    self->___reaction_1.function = __gendelay_197efreaction_function_1;
    self->___reaction_1.self = self;
    self->___reaction_1.num_outputs = 0;
    self->___reaction_1.output_produced = self->__reaction_1_outputs_are_present;
    self->___reaction_1.triggered_sizes = self->__reaction_1_triggered_sizes;
    self->___reaction_1.triggers = self->__reaction_1_triggers;
    self->___reaction_1.deadline_violation_handler = NULL;
    self->___act.scheduled = NEVER;
    self->___act_reactions[0] = &self->___reaction_0;
    self->___act.reactions = &self->___act_reactions[0];
    self->___act.number_of_reactions = 1;
    self->___act.is_physical = false;
    self->___act.drop = false;
    self->___act.element_size = sizeof(int);
    self->___inp.scheduled = NEVER;
    self->___inp_reactions[0] = &self->___reaction_1;
    self->___inp.reactions = &self->___inp_reactions[0];
    self->___inp.number_of_reactions = 1;
    self->___inp.element_size = sizeof(int);
    return self;
}
// =============== END reactor class __GenDelay_197ef

// =============== START reactor class Composition
typedef struct {
    bool hasContents;
} composition_self_t;
composition_self_t* new_Composition() {
    composition_self_t* self = (composition_self_t*)calloc(1, sizeof(composition_self_t));
    return self;
}
// =============== END reactor class Composition

void __set_default_command_line_options() {
}
// Array of pointers to timer triggers to start the timers in __start_timers().
trigger_t* __timer_triggers[1];
int __timer_triggers_size = 1;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    __tokens_with_ref_count_size = 1;
    __tokens_with_ref_count = (token_present_t*)malloc(1 * sizeof(token_present_t));
    // Create the array that will contain pointers to _is_present fields to reset on each step.
    __is_present_fields_size = 3;
    __is_present_fields = (bool**)malloc(3 * sizeof(bool*));
    // ************* Instance Composition of class Composition
    composition_self_t* composition_self = new_Composition();
    //***** Start initializing Composition
    // ************* Instance Composition.a of class A
    a_self_t* composition_a_self = new_A();
    //***** Start initializing Composition.a
    // Reaction 0 of Composition.a triggers 1 downstream reactions through port Composition.a._out.
    composition_a_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of Composition.a, allocate an
    // array of trigger pointers for downstream reactions through port Composition.a._out
    trigger_t** composition_a_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    composition_a_self->___reaction_0.triggers[0] = composition_a_0_0;
    composition_a_self->___startup.offset = 0;
    composition_a_self->___startup.period = 0;
    __timer_triggers[0] = &composition_a_self->___startup;
    composition_a_self->___out_num_destinations = 1;
    //***** End initializing Composition.a
    // ************* Instance Composition.b of class B
    b_self_t* composition_b_self = new_B();
    //***** Start initializing Composition.b
    // Reaction 0 of Composition.b triggers 1 downstream reactions through port Composition.b._out.
    composition_b_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of Composition.b, allocate an
    // array of trigger pointers for downstream reactions through port Composition.b._out
    trigger_t** composition_b_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    composition_b_self->___reaction_0.triggers[0] = composition_b_0_0;
    composition_b_self->___out_num_destinations = 1;
    //***** End initializing Composition.b
    // ************* Instance Composition.c of class C
    c_self_t* composition_c_self = new_C();
    //***** Start initializing Composition.c
    //***** End initializing Composition.c
    // ************* Instance Composition.delay of class __GenDelay_197ef
    __gendelay_197ef_self_t* composition_delay_self = new___GenDelay_197ef();
    //***** Start initializing Composition.delay
    composition_delay_self->delay = SEC(1);
    // Reaction 0 of Composition.delay triggers 1 downstream reactions through port Composition.delay.out.
    composition_delay_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of Composition.delay, allocate an
    // array of trigger pointers for downstream reactions through port Composition.delay.out
    trigger_t** composition_delay_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    composition_delay_self->___reaction_0.triggers[0] = composition_delay_0_0;
    composition_delay_self->___act.offset = SEC(1);
    composition_delay_self->___act.period = 0;
    composition_delay_self->__out_num_destinations = 1;
    composition_delay_self->___act.token = __create_token(sizeof(int));
    composition_delay_self->___act.is_present = false;
    __tokens_with_ref_count[0].token
            = &composition_delay_self->___act.token;
    __tokens_with_ref_count[0].is_present
            = &composition_delay_self->___act.is_present;
    __tokens_with_ref_count[0].reset_is_present = true;
    //***** End initializing Composition.delay
    //***** End initializing Composition
    // Populate arrays of trigger pointers.
    // Point to destination port Composition.b._in's trigger struct.
    composition_a_0_0[0] = &composition_b_self->____in;
    // Point to destination port Composition.delay.inp's trigger struct.
    composition_b_0_0[0] = &composition_delay_self->___inp;
    // Point to destination port Composition.c._in's trigger struct.
    composition_delay_0_0[0] = &composition_c_self->____in;
    // doDeferredInitialize
    composition_b_self->___in_is_present = &absent;
    composition_c_self->___in_is_present = &absent;
    composition_delay_self->__inp_is_present = &absent;
    // Connect inputs and outputs for reactor Composition.
    // Connect Composition.a._out to input port Composition.b._in
    composition_b_self->___in = &composition_a_self->___out;
    composition_b_self->___in_is_present = &composition_a_self->___out_is_present;
    // Connect Composition.b._out to input port Composition.delay.inp
    composition_delay_self->__inp = &composition_b_self->___out;
    composition_delay_self->__inp_is_present = &composition_b_self->___out_is_present;
    // Connect Composition.delay.out to input port Composition.c._in
    composition_c_self->___in = &composition_delay_self->__out;
    composition_c_self->___in_is_present = &composition_delay_self->__out_is_present;
    // Connect inputs and outputs for reactor Composition.a.
    // END Connect inputs and outputs for reactor Composition.a.
    // Connect inputs and outputs for reactor Composition.b.
    // END Connect inputs and outputs for reactor Composition.b.
    // Connect inputs and outputs for reactor Composition.c.
    // END Connect inputs and outputs for reactor Composition.c.
    // Connect inputs and outputs for reactor Composition.delay.
    // END Connect inputs and outputs for reactor Composition.delay.
    // END Connect inputs and outputs for reactor Composition.
    // Add port Composition.a._out to array of _is_present fields.
    __is_present_fields[0] = &composition_a_self->___out_is_present;
    // Add port Composition.b._out to array of _is_present fields.
    __is_present_fields[1] = &composition_b_self->___out_is_present;
    // Add port Composition.delay.out to array of _is_present fields.
    __is_present_fields[2] = &composition_delay_self->__out_is_present;
    composition_a_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    composition_a_self->___reaction_0.index = 0x7fffffffffff0000LL;
    composition_b_self->___reaction_0.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    composition_b_self->___reaction_0.index = 0x7fffffffffff0001LL;
    composition_c_self->___reaction_0.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    composition_c_self->___reaction_0.index = 0x7fffffffffff0001LL;
    composition_delay_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    composition_delay_self->___reaction_0.index = 0x7fffffffffff0000LL;
    composition_delay_self->___reaction_1.chain_id = 1;
    // index is the OR of level 2 and 
    // deadline 140737488355327 shifted left 16 bits.
    composition_delay_self->___reaction_1.index = 0x7fffffffffff0002LL;
}
void __start_timers() {
    
    for (int i = 0; i < __timer_triggers_size; i++) {
        __schedule(__timer_triggers[i], 0LL, NULL);
    }
}
void logical_time_complete(instant_t time) {
}
instant_t next_event_time(instant_t time) {
    return time;
}
bool __wrapup() {
    __start_time_step();   // To free memory allocated for actions.
    return false;
}
void __termination() {}
